# Generated by Django 5.2 on 2025-04-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('sub_category', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('market_price', models.FloatField()),
                ('sale_price', models.FloatField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
